In [ ]:
import numpy as np


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [2]:
print("#2")
import numpy as np
print(np.__version__)
np.show_config()

#2
1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Gangadhar/anaconda3/Library/include
    lib directory: C:/Users/Gangadhar/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows

In [4]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
z=np.zeros((10,10))
print("%d bytes" %(z.size * z.itemsize))

800 bytes


In [9]:
import numpy as np
z=np.zeros(10)
z[4] = 5
print(z)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


In [10]:
import numpy as np
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
import numpy as np
z=np.arange(50)
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [14]:
import numpy as np
z=np.arange(9)
print(z.reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [18]:
import numpy as np
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
import numpy as np
z = np.random.random((3,3,3))
print(z)

[[[0.69283119 0.24923634 0.35708535]
  [0.77003689 0.5163591  0.72176839]
  [0.70184387 0.88469774 0.77332943]]

 [[0.66268538 0.14510515 0.60563798]
  [0.21766312 0.50532909 0.84514917]
  [0.66569215 0.03930801 0.32540227]]

 [[0.24550973 0.25727089 0.12091237]
  [0.20785601 0.21492405 0.18590844]
  [0.47946064 0.70376859 0.38800898]]]


In [20]:
import  numpy as np
z=np.random.random((10,10))
zmin,zmax = z.min(), z.max()
print(zmin,zmax)

0.0018436089813412826 0.9705308616713444


In [21]:
import numpy as np
z = np.random.random(30)
m= z.mean()
print(m)

0.532055893229818


In [22]:
import numpy as np
z = np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
